spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.255.130:8848
    gateway:
      routes:
        - id: baidu_route
          uri: http://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: test_route
          uri: http://www.qq.com
          predicates:
            - Query=url,qq

  application:
    name: gateway


server:
  port: 88
